### Get All Pizzas
GET localhost:3000/pizzas

### Get Pizza By Id
GET localhost:3000/pizzas/64da00292dbe59499577ecfb

### Create Pizza By Id
POST localhost:3000/pizzas
Content-Type: application/json

{
  "price": {
    "S": 70000,
    "M": 100000,
    "L": 119000
  },
  "_id": "64df8af218f7c74b27d46df1",
  "name": "Test Pizza 1",
  "description": "Best pizza ever",
  "imageUrl": "https://mymenu.vn/assets/images/products/733/pizza-peperoni-mn-01.png",
  "category": "pizza",
  "orderCount": 0,
  "createdAt": "2023-08-18T15:14:58.480Z",
  "updatedAt": "2023-08-18T15:14:58.480Z",
  "__v": 0
}

### Update Pizza By Id
PUT localhost:3000/pizzas/64da00292dbe59499577ecfb
Content-Type: application/json

{
  "name": "Pizza 0"
}

### Delete Pizza By Id
DELETE localhost:3000/pizzas/64da00292dbe59499577ecfb